
# relevance

# The order in which orders will be sorted. Due to
# order dependencies, choosing a good order has some
# effect on efficiency.

relevance:
    convoy: 1
    hold: 4
    move: 2
    support: 3
